# Site settings
title: Jazztips
name: Jazztips
email: hej@urre.me
description: Tips om bra musik
# baseurl: ""
url: "https://jazztips.se"
logo: /images/og.png
timezone: Europe/Stockholm
locale: sv_SE
author:
  facebook: urbansanden
  twitter: urre
facebook:
  app_id: 184004771618651
  publisher: 191053684242292
  admins: 564494638
twitter:
  username: jazztps

# Pagination
paginate: 16
paginate_path: "/:num/"

# Build
buildtype: develop
limit_posts: 64

# Sass
sass:
  style: compact

# Exclude in build
exclude:
  - Gemfile
  - Gemfile.lock
  - bin
  - node_modules
  - index.js

# Tag page
tag_page_layout: tag_page
tag_page_dir: taggar
tag_permalink_style: pretty

# Gems
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll/tagging
- jekyll-paginate
