version: '3'
services:
  jekyll:
      image: jekyll/jekyll
      environment:
        - JEKYLL_ENV=development
      command: >
        bash -c "bundle install
        && bundle exec jekyll serve --force_polling --config _config-dev.yml --host 0.0.0.0"
      ports:
          - 4000:4000
      volumes:
          - .:/srv/jekyll
          - ./vendor/bundle:/usr/local/bundle
