name: Netlify Deploy

on:
  schedule:
  - cron: "0 12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Netlify Hook
      run: curl -X POST ${{ secrets.NETLIFY_BUILD_URL }}
